new Vue({
    el: "#app",
    data: {
        isActive:0,
        hotBook:[
            {
                href:"/",
                src:"../../img/150.jpg",
                name:"梦幻科技",
                author:"周焘"
            },
            {
                href:"/",
                src:"../../img/150.jpg",
                name:"梦幻科技",
                author:"周焘"
            },
            {
                href:"/",
                src:"../../img/150.jpg",
                name:"梦幻科技",
                author:"周焘"
            },
            {
                href:"/",
                src:"../../img/150.jpg",
                name:"梦幻科技",
                author:"周焘"
            },
            {
                href:"/",
                src:"../../img/150.jpg",
                name:"梦幻科技",
                author:"周焘"
            },
            {
                href:"/",
                src:"../../img/150.jpg",
                name:"梦幻科技",
                author:"周焘"
            }
        ],
        group: [
            {
                name: '热销榜',
                book:[
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技111",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技12",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技13",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技14",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技15",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技16",
                        author:"周焘"
                    }
                ]
            },
            {
                name: '点击榜',
                book:[
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技21",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技22",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技23",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技24",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技25",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技26",
                        author:"周焘"
                    }
                ]
            },
            {
                name: '推荐榜',
                book:[
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技31",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技32",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技33",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技34",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技35",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技36",
                        author:"周焘"
                    }
                ]
            },
            {
                name: '新书榜',
                book:[
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技41",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技42",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技43",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技44",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技45",
                        author:"周焘"
                    },
                    {
                        href:"/",
                        src:"../../img/150.jpg",
                        name:"梦幻科技46",
                        author:"周焘"
                    }
                ]
            }
        ],
        newBook:[
            {
                href:"/",
                src:"../../img/150.jpg",
                name:"梦幻科技",
                author:"周焘",
                profile:"阿萨撒大声地撒啊尴尬个可能发生那谁都卡死你的萨克的",
                type:"科幻"
            },
            {
                href:"/",
                src:"../../img/150.jpg",
                name:"梦幻科技",
                author:"周焘",
                profile:"阿萨撒大声地撒啊尴尬个可能发生那谁都卡死你的萨克的",
                type:"科幻"
            },
            {
                href:"/",
                src:"../../img/150.jpg",
                name:"梦幻科技",
                author:"周焘",
                profile:"阿萨撒大声地撒啊尴尬个可能发生那谁都卡死你的萨克的",
                type:"科幻"
            },
            {
                href:"/",
                src:"../../img/150.jpg",
                name:"梦幻科技",
                author:"周焘",
                profile:"阿萨撒大声地撒啊尴尬个可能发生那谁都卡死你的萨克的",
                type:"科幻"
            },
            {
                href:"/",
                src:"../../img/150.jpg",
                name:"梦幻科技",
                author:"周焘",
                profile:"阿萨撒大声地撒啊尴尬个可能发生那谁都卡死你的萨克的",
                type:"科幻"
            },
            {
                href:"/",
                src:"../../img/150.jpg",
                name:"梦幻科技",
                author:"周焘",
                profile:"阿萨撒大声地撒啊尴尬个可能发生那谁都卡死你的萨克的",
                type:"科幻"
            }
        ],
        endBook:[
            {
                href:"/",
                src:"../../img/150.jpg",
                name:"梦幻科技",
                author:"周焘",
                profile:"阿萨撒大声地撒啊尴尬个可能发生那谁都卡死你的萨克的",
                type:"科幻"
            },
            {
                href:"/",
                src:"../../img/150.jpg",
                name:"梦幻科技",
                author:"周焘",
                profile:"阿萨撒大声地撒啊尴尬个可能发生那谁都卡死你的萨克的",
                type:"科幻"
            },
            {
                href:"/",
                src:"../../img/150.jpg",
                name:"梦幻科技",
                author:"周焘",
                profile:"阿萨撒大声地撒啊尴尬个可能发生那谁都卡死你的萨克的",
                type:"科幻"
            },
            {
                href:"/",
                src:"../../img/150.jpg",
                name:"梦幻科技",
                author:"周焘",
                profile:"阿萨撒大声地撒啊尴尬个可能发生那谁都卡死你的萨克的",
                type:"科幻"
            },
            {
                href:"/",
                src:"../../img/150.jpg",
                name:"梦幻科技",
                author:"周焘",
                profile:"阿萨撒大声地撒啊尴尬个可能发生那谁都卡死你的萨克的",
                type:"科幻"
            },
            {
                href:"/",
                src:"../../img/150.jpg",
                name:"梦幻科技",
                author:"周焘",
                profile:"阿萨撒大声地撒啊尴尬个可能发生那谁都卡死你的萨克的",
                type:"科幻"
            }
        ]
    },
    methods: {
        change: function (index) {
            this.isActive = index;
        }
    }
});